# Quarkus Application Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsrv-mutiny

spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsrv-mutiny
  template:
    metadata:
      labels:
        app: appsrv-mutiny
    spec:
      containers:
        - name: appsrv
          image: ghcr.io/2425-5bhif-wmc/01-referate-icqun/mutiny-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          startupProbe:
            httpGet:
              path: /q/health
              port: 8081
            timeoutSeconds: 5
            initialDelaySeconds: 15
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /q/health
              port: 8081
            timeoutSeconds: 5
            initialDelaySeconds: 60
            periodSeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  name: appsrv-mutiny

spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: appsrv-mutiny