name: Build Docker images
run-name: ${{ github.actor }} is building Docker images 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-images:
    permissions: write-all
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./classic-demo/src/main/docker/Dockerfile
            context: ./classic-demo
            tag: ghcr.io/icqun/classic-demo:latest
          - dockerfile: ./mutiny-demo/src/main/docker/Dockerfile
            context: ./mutiny-demo
            tag: ghcr.io/icqun/mutiny-demo:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context:  ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ matrix.tag }}